### PR TITLE
docs(readme): add badges

### LINKED ISSUE #180: Add badges to README
Add generic badges to the README, such as test status, doc building, and code coverage.

Snapcraft and charmcraft are good references.

### PR DESCRIPTION
**Pull request by lengau**
Fixes #180

- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox`?

-----

### CODE REVIEW

**Review by mattculler — APPROVED** [review]
Not sure what the correct way is to fix that "line too long" linter failure when the doc line is a URL - I would almost expect the linter to be aware that you can't wrap URLs.

**Comment by mr-cal** [comment]
> Not sure what the correct way is to fix that "line too long" linter failure when the doc line is a URL - I would almost expect the linter to be aware that you can't wrap URLs.

I was fighting that last week on a personal repo.

These badges in craft-providers ([here](https://github.com/canonical/craft-providers/blob/6f5e285ee1c20f3ad2bcf537fa112d79d5081c73/README.rst?plain=1#L37)) used to work and outsmarted the `sphinx-lint` line-length rules.  But that syntax broke on Github in the last month or so and they don't render well anymore.

Github does a bad job rendering RST and I found many comments to the same effect in Github's issue tracker.

I wasn't able to find any way with `sphinx-lint` to disable line-length for URLs.

**Comment by mattculler** [comment]
> > Not sure what the correct way is to fix that "line too long" linter failure when the doc line is a URL - I would almost expect the linter to be aware that you can't wrap URLs.
> 
> I was fighting that last week on a personal repo.
> 
> These badges in craft-providers ([here](https://github.com/canonical/craft-providers/blob/6f5e285ee1c20f3ad2bcf537fa112d79d5081c73/README.rst?plain=1#L37)) used to work and outsmarted the `sphinx-lint` line-length rules. But that syntax broke on Github in the last month or so and they don't render well anymore.
> 
> Github does a bad job rendering RST and I found many comments to the same effect in Github's issue tracker.
> 
> I wasn't able to find any way with `sphinx-lint` to disable line-length for URLs.

Found this issue: https://github.com/pylint-dev/pylint/issues/2178

Seems like sphinx does ignore long lines for URLs by default, but that fails here since the URL isn't at the start of the line.

https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#ignore-long-lines

So either you have to format your badge RST to put the URL on its own line, or modify sphinx's `ignore-long-lines` regex to ignore badge lines.

**Comment by tigarmo** [comment]
Here's one possible suggestion for handling the line-length issue (not sure if it'll actually work): put the URLs in a separate "urls.txt" file, `.. include` it at the bottom of the README and then pass `--ignore urls.txt` to the sphinx-lint call

**Comment by lengau** [comment]
Honestly I'm tempted to just get rid of the `line-too-long` linter for docs files. Static word wrapping is great for code, but I'm not sure it really matters as much with documentation since most text editors do a good job of wrapping the documentation lines anyway. What do you think @mr-cal @mattculler @tigarmo ?

**Comment by tigarmo** [comment]
well the real final boss you have to convince here is @sergiusens

**Comment by mattculler** [comment]
@lengau FWIW I completely agree - hard line breaks are essential for code but don't make sense for docs.

**Comment by mr-cal** [comment]
+1 on dropping line length linting for docs because the tooling isn't good enough right now:

- no auto-formatting to break lines
- no way to disable the linter

**Comment by sergiusens** [comment]
Personally not a fan,  in the sense that the whole point of these simple markup files is that you can read them without processing them and the presentation might require certain structure.

That said, this should be a soft requirement, I do not care for the linters. If we remove it, let's remove it for all, not just docs.

**Comment by mr-cal** [comment]
Badge issue will be fixed via https://github.com/canonical/starbase/issues/233

**Comment by mr-cal** [comment]
Is this passing now because of https://github.com/canonical/starbase/pull/221 ?

**Comment by lengau** [comment]
@mr-cal lol I guess. Nice!

**Pull request merged**
